### ISSUE TITLE
Cannot read properties of undefined (reading 'Symbol(TAG_COMPUTE)')

### ISSUE THREAD

**Issue by wagenet** [glimmerjs/glimmer-vm#1369]
```
global failure: TypeError: Cannot read properties of undefined (reading 'Symbol(TAG_COMPUTE)')@ 398 ms
Source:     
TypeError: Cannot read properties of undefined (reading 'Symbol(TAG_COMPUTE)')
    at validateTag (http://localhost:7357/assets/vendor.js:58940:27)
    at valueForRef (http://localhost:7357/assets/vendor.js:49853:53)
    at http://localhost:7357/assets/vendor.js:49949:40
    at http://localhost:7357/assets/vendor.js:49858:37
    at track (http://localhost:7357/assets/vendor.js:59446:7)
    at valueForRef (http://localhost:7357/assets/vendor.js:49857:44)
    at NamedArgsProxy.get (http://localhost:7357/assets/vendor.js:45044:43)
    at RangeLabelComponent.get ariaLabel [as ariaLabel] (http://localhost:7357/assets/direwolf.js:17574:21)
    at getPossibleMandatoryProxyValue (http://localhost:7357/assets/vendor.js:18979:19)
    at _getProp (http://localhost:7357/assets/vendor.js:19044:17)
```

This was triggered by an Ember test that failed to specify `this` for HBS properties:

```ts
    this.set('range', 'my-range');

    await render(
      hbs`<SelectedTimeRange @range={{range} />`
    );
```

Specifying it correctly as `{{this.range}}` solved the issue.

**Comment by NullVoxPopuli** [comment]
I think we can improve the error message here.
Not sure what it could say, but maybe something along these lines?
```
Cannot read properties of undefined (reading 'Symbol(TAG_COMPUTE)')
Encountered `{{range}}`, which did not resolve to anything. 
does `this` need to be added?
Is it in the global scope?
```
