### ISSUE TITLE
Using handlebars helpers in a Custom Element raises error

### ISSUE THREAD

**Issue by dunnkers** [glimmerjs/glimmer-vm#554]
## Problem
A compilation error is thrown when a helper like `{{action}}` is used inside a custom element. e.g.

```hbs
<paper-button raised {{action 'signIn'}}>Sign in</paper-button>
```

throws the following error:

<details><summary>Error: Compile Error: Element modifiers are not allowed in components</summary><p>

```shell
File: dummy/templates/index.hbs
The Broccoli Plugin: [broccoli-persistent-filter:TemplateCompiler] failed with:
Error: Compile Error: Element modifiers are not allowed in components
    at ComponentBlock.push (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-template-co
mpiler.js:481:27)
    at JavaScriptCompiler.push (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-templat
e-compiler.js:750:33)
    at JavaScriptCompiler.modifier (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-tem
plate-compiler.js:594:18)
    at /Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-template-compiler.js:549:31
    at Array.forEach (native)
    at JavaScriptCompiler.process (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-temp
late-compiler.js:541:26)
    at Function.process (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-template-compi
ler.js:535:29)
    at Function.compile (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-template-compi
ler.js:784:39)
    at precompile (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-template-compiler.js
:1292:58)
    at Object.precompile (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-source/dist/ember-template-comp
iler.js:15386:12)

The broccoli plugin was instantiated at:
    at TemplateCompiler.Plugin (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/broccoli-plugin/index.js:7:31)
    at TemplateCompiler.Filter [as constructor] (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/broccoli-persi
stent-filter/index.js:62:10)
    at TemplateCompiler (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-cli-htmlbars/index.js:18:5)
    at Object.toTree (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-cli-htmlbars/ember-addon-main.js:23
:16)
    at /Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-cli-preprocess-registry/preprocess
ors.js:178:11)
    at module.exports.preprocessTemplates (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-cli-preprocess
-registry/preprocessors.js:161:10)
    at EmberAddon._processedTemplatesTree (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-cli/lib/brocco
li/ember-app.js:881:50)
    at EmberAddon.appAndDependencies (/Users/Dunnkers/Documents/git/ember-polymer/node_modules/ember-cli/lib/broccoli/em
ber-app.js:1099:26)
```

</p></details>

<br>

→ See https://github.com/dunnkers/ember-polymer/issues/65

## Cause
The error is thrown at [javascript-compiler.ts#L91](https://github.com/glimmerjs/glimmer-vm/blob/9fb4cd315589186ce7179bed4015d56764001ee7/packages/%40glimmer/compiler/lib/javascript-compiler.ts#L91). Accompanying test: [ember-component-test.ts#L2474](https://github.com/glimmerjs/glimmer-vm/blob/bb64d10a82d5fd5bb96c40a5b88ec94bbae2801d/packages/%40glimmer/runtime/test/ember-component-test.ts#L2474).

## Reproduction:
http://jsbin.com/cuyatamojo/edit?html,output

```html
<some-custom-button-element {{action "some-action"}}>
  Do some cool action!
</some-custom-button-element>
```

**Comment by locks** [comment]
You need to explicitly bind the `onclick` event like so: `onclick={{action "some-action"}}`.
