### ISSUE TITLE
Broccoli Plugin failed: block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by eelke** [glimmerjs/glimmer-vm#579]
I have updated NPM, Updated ember-cli to 2.14.0 following the [release note instructions](https://github.com/ember-cli/ember-cli/releases/tag/v2.14.0).

I have then created a new Glimmer project, following the glimmer instructions, and then try to start the server, which fails due to some strict mode error:

````
$ ember new afk-subsidiewijzer -b @glimmer/blueprint

installing blueprint
  create .editorconfig
  create .watchmanconfig
  create README.md
  create config/environment.js
  create config/module-map.d.ts
  create config/resolver-configuration.d.ts
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create src/index.ts
  create src/main.ts
  create src/ui/components/afk-subsidiewijzer/component-test.ts
  create src/ui/components/afk-subsidiewijzer/component.ts
  create src/ui/components/afk-subsidiewijzer/template.hbs
  create src/ui/index.html
  create src/ui/styles/app.scss
  create src/utils/test-helpers/test-helper.ts
  create testem.json
  create tsconfig.json
  create yarn.lock
Yarn: Installed dependencies
Successfully initialized git.

$ cd afk-subsidiewijzer/ && ember s
Livereload server on http://localhost:49153
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Project.require (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/ember-cli/lib/models/project.js:322:14)
    at Project.targets (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/ember-cli/lib/models/project.js:238:28)
    at RollupWithDependencies.build (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/rollup-with-dependencies.js:64:38)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/@glimmer/application-pipeline/node_modules/broccoli-merge-trees/index.js:16:10)
    at GlimmerApp.package (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:256:23)
    at GlimmerApp.toTree (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:287:28)
    at module.exports (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/ember-cli-build.js:10:14)
    at Builder.setupBroccoliBuilder (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at /Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/ember-cli/lib/models/command.js:243:46
    at tryCatch (/Users/eelke/Documents/Werk/Server/afk/afk-subsidiewijzer/node_modules/rsvp/dist/rsvp.js:525:12)


cleaning up...

**Comment by Cryrivers** [comment]
Not sure if it helps, but you can try adding `IE 11` to `config/targets.js`.

**Comment by twokul** [comment]
@eelke could you run `ember --version --verbose` and paste the output?

**Comment by eelke** [comment]
@Cryrivers That did not fix it
@twokul Sure, see below

    ember-cli: 2.14.0
    http_parser: 2.7.0
    node: 4.7.2
    v8: 4.5.103.43
    uv: 1.9.1
    zlib: 1.2.8
    ares: 1.10.1-DEV
    icu: 56.1
    modules: 46
    openssl: 1.0.2j
    os: darwin x64

**Comment by twokul** [comment]
@eelke try bumping your version of node.js to anything `4.8+`, ideally to `7+` if you can

**Comment by eelke** [comment]
I have switched over to Node 7.10.1 (current v7 version) and now the server works fine. Thank you @twokul. I will close the issue, but want to point out that the Glimmer.js documentation currently states: `Ember requires Node.js 4 or higher and npm 2.14.2 or higher.`. That might need an update?

**Comment by twokul** [comment]
@eelke yes, Good Sir, I believe you are correct. Thanks for flagging this!
